name: srv-configuration
group: robotic-framework
owner: robotic-framework
version: 0.0.0
description: configuration of general purpose
program_language: golang
workflow:
  extends: feature-pr
scripts:
  build:
  - go build -v -o ./build/$PROJECT_NAME ./cmd
  - eden generate openapi
  test: go test ./cmd
